version: '3.8'

services:
  # 1. Database: MongoDB
  mongo:
    image: mongo:6.0
    container_name: pikaflow-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  # 2. Queue & Cache: Redis
  redis:
    image: redis:alpine
    container_name: pikaflow-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: